kind: Service
apiVersion: v1
metadata:
  name: blissfish-blackstar
  namespace: default
  labels: 
    run: blissfish-blackstar
spec: 
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector: 
    run: blissfish-blackstar
  type: LoadBalancer
    
